environment: development
name: ffc-helm-only-example
namespace: ffc-demo
workstream: ffc-demo

labels: {}

ingress:
  class: nginx
  endpoint: ffc-helm-only-example
  server: example.com
  type: master

service:
  port: 80
  type: ClusterIP

secret:
  name: ffc-demo-basic-auth
  type: Opaque